services:
  postgres:
    image: postgres:15
    container_name: ingressos_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: ingressos_redis
    ports:
      - "6379:6379"

  auth:
    build:
      context: ./auth
    env_file:
      - ./auth/.env
    deploy:
      replicas: 2
    depends_on:
      postgres:
        condition: service_healthy

  events:
    build:
      context: ./events
    env_file:
      - ./events/.env
    deploy:
      replicas: 2
    depends_on:
      postgres:
        condition: service_healthy

  orders:
    build:
      context: ./orders
    env_file:
      - ./orders/.env
    deploy:
      replicas: 2
    depends_on:
      postgres:
        condition: service_healthy
      events:
        condition: service_started
      payments:
        condition: service_started

  payments:
    build:
      context: ./payments
    env_file:
      - ./payments/.env
    deploy:
      replicas: 2
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    image: nginx:alpine
    container_name: ingressos_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - events
      - orders
      - payments

  prometheus:
    image: prom/prometheus:latest
    container_name: ingressos_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - auth
      - events
      - orders
      - payments



volumes:
  postgres_data:
